sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t emberone/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true emberone/docker-react npm run test
